# Generated by Django 3.1.1 on 2022-03-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20220329_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.CharField(default='', max_length=64),
        ),
    ]
